// constants/icons.ts

export const ICONS = {
  accountCircle: require('../assets/icons/account_circle.png'),
  activity: require('../assets/icons/Activity.png'),
  arrowRightCircle: require('../assets/icons/Arrow_right_circle.png'),
  arrowright: require('../assets/icons/arrow_right.png'),
  arrowLeft: require('../assets/icons/Arrow_left.png'),
  arrowdown: require('../assets/icons/arrowdown.png'),
  camera: require('../assets/icons/Camera.png'),
  calendar: require('../assets/icons/Canlendar.png'),
  checkBoxDark: require('../assets/icons/check_box_dark.png'),
  xlight: require('../assets/icons/x_light.png'),
  checkBoxLight: require('../assets/icons/check_box_light.png'),
  checkSquare: require('../assets/icons/Check_square.png'),
  clock: require('../assets/icons/Clock.png'),
  comment: require('../assets/icons/comment.png'),
  dot: require('../assets/icons/dot.png'),
  helpCircle: require('../assets/icons/Help_circle.png'),
  home: require('../assets/icons/Home.png'),
  language: require('../assets/icons/language.png'),
  lock: require('../assets/icons/Lock.png'),
  map: require('../assets/icons/Map.png'),
  mapPin: require('../assets/icons/Map_pin.png'),
  messageSquare: require('../assets/icons/Message_square.png'),
  navigation: require('../assets/icons/Navigation.png'),
  notifications: require('../assets/icons/notifications.png'),
  settings: require('../assets/icons/Settings.png'),
  user: require('../assets/icons/User.png'),
  userPlus: require('../assets/icons/User_plus.png'),
  users: require('../assets/icons/Users.png'),
  search: require('../assets/icons/search.png'),
  coach: require('../assets/icons/coach.png'),
  player: require('../assets/icons/player.png'),
  court: require('../assets/icons/court.png'),
  mic: require('../assets/icons/mic.png'),
  location_icon: require('../assets/icons/location.png'),
  ggmap: require('../assets/icons/ggmap.png'),
  app_icon: require('../assets/icons/placeholder_icon.png'),
  eye: require('../assets/icons/Eye.png'),
  notEye: require('../assets/icons/notEye.png'),
  check: require('../assets/icons/Check.png'),
  checkSmall: require('../assets/icons/check_small.png'),
  tableTennis: require('../assets/icons/table_tennis.png'),
  badminton: require('../assets/icons/badminton.png'),
  golf: require('../assets/icons/golf.png'),
  availCategory: require('../assets/icons/avail_category.png'),
  sportCategory: require('../assets/icons/sport_category.png'),
  venueCategory: require('../assets/icons/venue_category.png'),
  indoor: require('../assets/icons/indoor.png'),
  football: require('../assets/icons/football.png'),
  basketball: require('../assets/icons/basketball.png'),
  running: require('../assets/icons/running.png'),
  volleyball: require('../assets/icons/volleyball.png'),
  pickleball: require('../assets/icons/pickleball.png'),
  outdoor: require('../assets/icons/outdoor.png'),
  x: require('../assets/icons/x.png'),
  tick: require('../assets/icons/tick.png'),
  supportCentre: require('../assets/icons/support_centre.png'),
  starCal: require('../assets/icons/star_cal.png'),
  coachCal: require('../assets/icons/coach_cal.png'),
  stadiumCal: require('../assets/icons/stadium_cal.png'),
  event_category: require('../assets/icons/event.png'),
}; 


////
export const IMP_ICONS ={
    adaptiveIcon: require('../assets/icons/import_icons/adaptiveicon.png'),
    favIcon: require('../assets/icons/import_icons/favicon.png'),
    icon: require('../assets/icons/import_icons/icon.png'),
    partialReactLogo: require('../assets/icons/import_icons/partialreactlogo.png'),
    reactLogo: require('../assets/icons/import_icons/reactlogo.png'),
    reactLogo2x: require('../assets/icons/import_icons/reactlogo2x.png'),
    reactlogo3x: require('../assets/icons/import_icons/reactlogo3x.png'),
    splashIcon: require('../assets/icons/import_icons/splashicon.png'),
    spaceMonoRegular: require('../assets/icons/import_icons/SpaceMono-Regular.ttf')
}
