-- Performance hotfixes and anti-pattern migrations for SportConnect.
-- Run in Supabase SQL editor in a maintenance window.

begin;

-- 1) Enforce double-booking prevention at the database layer.
create extension if not exists btree_gist;

drop index if exists public.courtbooking_no_overlap;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'courtbooking_no_overlap_excl'
      and conrelid = 'public.courtbooking'::regclass
  ) then
    alter table public.courtbooking
      add constraint courtbooking_no_overlap_excl
      exclude using gist (
        playingcourtid with =,
        tsrange(start_timestamp, end_timestamp, '[)') with &&
      )
      where (
        playingcourtid is not null
        and bookingstatus = 'upcoming'::sessionstatus
      );
  end if;
end $$;

-- 2) Migrate next_gap_id defaults to native IDENTITY columns.
-- next_gap_id scans for holes and can serialize inserts under concurrency.
create or replace function public.migrate_gap_id_default_to_identity(p_table regclass, p_column name)
returns void
language plpgsql
as $$
declare
  default_expr text;
  max_id bigint;
  seq_name text;
begin
  select pg_get_expr(d.adbin, d.adrelid)
    into default_expr
  from pg_attrdef d
  join pg_attribute a
    on a.attrelid = d.adrelid
   and a.attnum = d.adnum
  where d.adrelid = p_table
    and a.attname = p_column;

  if default_expr is null or default_expr not like 'next_gap_id(%' then
    raise notice 'Skipping %.% because default is %', p_table::text, p_column, coalesce(default_expr, '<none>');
    return;
  end if;

  execute format('select coalesce(max(%I), 0) from %s', p_column, p_table) into max_id;
  execute format('alter table %s alter column %I drop default', p_table, p_column);
  execute format('alter table %s alter column %I add generated by default as identity', p_table, p_column);

  select pg_get_serial_sequence(p_table::text, p_column::text) into seq_name;
  perform setval(seq_name, max_id + 1, false);
end $$;

select public.migrate_gap_id_default_to_identity('public.block_list', 'blockid');
select public.migrate_gap_id_default_to_identity('public.courtavailability', 'availabilityid');
select public.migrate_gap_id_default_to_identity('public.courtbooking', 'courtbookingid');
select public.migrate_gap_id_default_to_identity('public.courtinfo', 'courtinfoid');
select public.migrate_gap_id_default_to_identity('public.courts', 'courtid');
select public.migrate_gap_id_default_to_identity('public.eventbooking', 'eventbookingid');
select public.migrate_gap_id_default_to_identity('public.eventinfo', 'eventinfoid');
select public.migrate_gap_id_default_to_identity('public.events', 'eventid');
select public.migrate_gap_id_default_to_identity('public.favouritecourts', 'favouriteid');
select public.migrate_gap_id_default_to_identity('public.notifications', 'notificationid');
select public.migrate_gap_id_default_to_identity('public.payments', 'paymentid');
select public.migrate_gap_id_default_to_identity('public.reviews', 'reviewid');
select public.migrate_gap_id_default_to_identity('public.trainingsessioninfo', 'sessioninfoid');
select public.migrate_gap_id_default_to_identity('public.trainingsessions', 'sessionid');
select public.migrate_gap_id_default_to_identity('public.tsbookings', 'tsbookingid');
select public.migrate_gap_id_default_to_identity('public.unverified_users', 'unverifiedid');
select public.migrate_gap_id_default_to_identity('public.user_tokens', 'tokenid');
select public.migrate_gap_id_default_to_identity('public.userinfo', 'infoid');
select public.migrate_gap_id_default_to_identity('public.userlogin', 'loginid');
select public.migrate_gap_id_default_to_identity('public.users', 'userid');

drop function if exists public.migrate_gap_id_default_to_identity(regclass, name);

commit;

-- 3) Long-term schedule normalization to replace JSONB booking_date filters.
-- Recommended design: schedule rules in a child table, then derive bookable slots.
create table if not exists public.court_schedule_rules (
  schedule_rule_id bigint generated by default as identity primary key,
  courtid integer not null references public.courts(courtid) on delete cascade,
  playingcourtid bigint references public.playingcourt(playingcourtid) on delete cascade,
  day_of_week smallint not null check (day_of_week between 0 and 6),
  valid_from date not null,
  valid_to date,
  start_time time not null,
  end_time time not null,
  is_available boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists idx_court_schedule_rules_lookup
  on public.court_schedule_rules (courtid, playingcourtid, day_of_week, valid_from, valid_to);

-- Migration strategy:
-- 1. Backfill recurring schedule rules from existing JSONB booking_date data.
-- 2. Add a real DATE column on new availability rows, sourced from court_schedule_rules.
-- 3. Move reads to the DATE-backed table/view.
-- 4. Remove JSONB booking_date once all callers use the normalized model.