// constants/icons.ts

export const ICONS = {
  accountCircle: require('../assets/icons/account_circle.png'),
  activity: require('../assets/icons/Activity.png'),
  arrowRightCircle: require('../assets/icons/Arrow_right-circle.png'),
  camera: require('../assets/icons/Camera.png'),
  calendar: require('../assets/icons/Canlendar.png'),
  checkBoxDark: require('../assets/icons/check_box_dark.png'),
  checkBoxLight: require('../assets/icons/check_box_light.png'),
  checkSquare: require('../assets/icons/Check_square.png'),
  clock: require('../assets/icons/Clock.png'),
  comment: require('../assets/icons/comment.png'),
  dot: require('../assets/icons/dot.png'),
  helpCircle: require('../assets/icons/Help_circle.png'),
  home: require('../assets/icons/Home.png'),
  language: require('../assets/icons/language.png'),
  lock: require('../assets/icons/Lock.png'),
  map: require('../assets/icons/Map.png'),
  mapPin: require('../assets/icons/Map_pin.png'),
  messageSquare: require('../assets/icons/Message_square.png'),
  navigation: require('../assets/icons/Navigation.png'),
  notifications: require('../assets/icons/notifications.png'),
  settings: require('../assets/icons/Settings.png'),
  user: require('../assets/icons/User.png'),
  userPlus: require('../assets/icons/User_plus.png'),
  users: require('../assets/icons/Users.png'),
  search: require('../assets/icons/search.png'),
  coach: require('../assets/icons/coach.png'),
  player: require('../assets/icons/player.png'),
  court: require('../assets/icons/court.png'),
};