//testing data 
export const markers = [
  {
    name: "Hanoi Sports Complex",
    address: "123 Tran Phu, Hanoi",
    latitude: 21.0285,
    longitude: 105.8542,
    latitudeDelta: 0.05,
    longitudeDelta: 0.05,
    images: ["https://via.placeholder.com/100", "https://via.placeholder.com/100"],
    venue: "Outdoor",
    availability: "Available",
  },
  {
    name: "Saigon Football Field",
    address: "456 Le Loi, Ho Chi Minh City",
    latitude: 10.7626,
    longitude: 106.6602,
    latitudeDelta: 0.05,
    longitudeDelta: 0.05,
    images: ["https://via.placeholder.com/100", "https://via.placeholder.com/100"],
    venue: "Outdoor",
    availability: "Unavailable",
  },
  {
    name: "Da Nang Sports Center",
    address: "789 Vo Nguyen Giap, Da Nang",
    latitude: 16.0471,
    longitude: 108.2068,
    latitudeDelta: 0.05,
    longitudeDelta: 0.05,
    images: ["https://via.placeholder.com/100", "https://via.placeholder.com/100"],
    venue: "Indoor",
    availability: "Available",
  },
  {
    name: "Hue Tennis Club",
    address: "12 Nguyen Hue, Hue",
    latitude: 16.4637,
    longitude: 107.5909,
    latitudeDelta: 0.05,
    longitudeDelta: 0.05,
    images: ["https://via.placeholder.com/100", "https://via.placeholder.com/100"],
    venue: "Outdoor",
    availability: "Available",
  },
  {
    name: "Nha Trang Beach Courts",
    address: "Beachfront, Nha Trang",
    latitude: 12.2388,
    longitude: 109.1967,
    latitudeDelta: 0.05,
    longitudeDelta: 0.05,
    images: ["https://via.placeholder.com/100", "https://via.placeholder.com/100"],
    venue: "Outdoor",
    availability: "Unavailable",
  },
  {
    name: "Vinh Sports Hall",
    address: "45 Le Duan, Vinh",
    latitude: 18.6714,
    longitude: 105.6871,
    latitudeDelta: 0.05,
    longitudeDelta: 0.05,
    images: ["https://via.placeholder.com/100", "https://via.placeholder.com/100"],
    venue: "Indoor",
    availability: "Available",
  },
  {
    name: "Can Tho Community Courts",
    address: "9 Le Loi, Can Tho",
    latitude: 10.0452,
    longitude: 105.7469,
    latitudeDelta: 0.05,
    longitudeDelta: 0.05,
    images: ["https://via.placeholder.com/100", "https://via.placeholder.com/100"],
    venue: ["Indoor", "Outdoor"], // both
    availability: "Available",
  },
  {
    name: "Bien Hoa Pickleball Park",
    address: "Address: 21 Hung Vuong, Bien Hoa",
    latitude: 10.9535,
    longitude: 106.8239,
    latitudeDelta: 0.05,
    longitudeDelta: 0.05,
    images: ["https://via.placeholder.com/100", "https://via.placeholder.com/100"],
    venue: "Outdoor",
    availability: "Available",
  },
  {
    name: "Ha Long Community Center",
    address: "Harbor Rd, Ha Long",
    latitude: 20.96,
    longitude: 107.0447,
    latitudeDelta: 0.05,
    longitudeDelta: 0.05,
    images: ["https://via.placeholder.com/100", "https://via.placeholder.com/100"],
    venue: ["Indoor", "Outdoor"], // both
    availability: "Unavailable",
  },
  {
    name: "Pleiku Running Track",
    address: "Route 14, Pleiku",
    latitude: 13.9833,
    longitude: 108.0,
    latitudeDelta: 0.05,
    longitudeDelta: 0.05,
    images: ["https://via.placeholder.com/100", "https://via.placeholder.com/100"],
    venue: "Outdoor",
    availability: "Available",
  },
  {
    name: "Dong Nai Indoor Courts",
    address: "88 Nguyen An Ninh, Dong Nai",
    latitude: 10.9685,
    longitude: 106.8231,
    latitudeDelta: 0.05,
    longitudeDelta: 0.05,
    images: ["https://via.placeholder.com/100", "https://via.placeholder.com/100"],
    venue: "Indoor",
    availability: "Unavailable",
  },
  {
    name: "Kon Tum Golf Range",
    address: "Golf Rd, Kon Tum",
    latitude: 14.349,
    longitude: 107.9777,
    latitudeDelta: 0.05,
    longitudeDelta: 0.05,
    images: ["https://via.placeholder.com/100", "https://via.placeholder.com/100"],
    venue: "Outdoor",
    availability: "Available",
  },
];
